### ISSUE TITLE
UI and Contents

### ISSUE THREAD

**Issue by Jsueeee** [euphony-io/here-is-my-card#2]
@psh2849 @seoh02h @sunnnl 
I'm designing an app.
There are four things we decided to put on our business cards.
1. name
2. tel
3. e-mail
4. company

I searched for 'business cards' on Google, but they seem to use addresses mostly. 

![image](https://user-images.githubusercontent.com/66951780/129680893-5d5adc85-bd53-4868-9179-12b0ec04f2d8.png)

How about changing company to **address** ?

**Comment by seohy02** [comment]
That's good !

**Comment by psh2849** [comment]
Good! I agree
