### ISSUE TITLE
[Error] UI doesn't seem right in some devices.

### ISSUE THREAD

**Issue by sunnnl** [euphony-io/here-is-my-card#23]
## Title
[Error] UI doesn't seem right in some devices.
## Description
It seems there is a crack when using device with different ratio.
I used Galaxy S5 which has a resolution of 1080 × 1920.
Would you please fix to support a variety of devices?
## Current Behavior
![Screenshot_2021-08-28-02-23-30](https://user-images.githubusercontent.com/83627611/131166200-f09fb9b3-8daf-40a8-a95d-c603c272e350.png)

**Comment by Jsueeee** [comment]
I think because the view ratio isn't right.
It seems that the app is running on a device with a small screen.
looks easy I will fix it and upload it.

**Comment by Jsueeee** [comment]
I updated PR for this Issue.
It was fine when I tested it in 1080 × 1920 avd, please check it on the your device with the problem.
