### ISSUE TITLE
set .gitignore

### ISSUE THREAD

**Issue by sunnnl** [euphony-io/here-is-my-card#7]
Please write any language or framework to add on .gitignore
@psh2849 @seoh02h @Jsueeee

**Comment by seohy02** [comment]
I think it would be good to use https://www.toptal.com/developers/gitignore.

**Comment by seohy02** [comment]
When searching for 'android studio', the results are as follows:
https://www.toptal.com/developers/gitignore/api/androidstudio

**Comment by seohy02** [comment]
When searching for 'android', the results are as follows:
https://www.toptal.com/developers/gitignore/api/android
